---
title: "BVI literature review"
author: "Seewoo Li"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(openai)
library(bibliometrix)
library(tidyverse)
library(glue)
library(xlsx)
library(jsonlite)

get_completion <- function(prompt, model = "gpt-4o", temperature = 0){
  messages <- list(
    list(
      "role" = "system",
      "content" = "You are an expert in conducting literature review."
    ),
    list(
      "role" = "user",
      "content" = prompt
    )
  )
  res <- openai::create_chat_completion(
    model = model,
    messages = messages,
    temperature = temperature
  )
  message(paste("Used tokens:", res$usage$prompt_tokens, "+", res$usage$completion_tokens, "=",  res$usage$total_tokens))
  message(paste("Price: $", res$usage$prompt_tokens/1000000*5+res$usage$prompt_tokens/1000000*15))
  return(res$choices$message.content)
}
```


# Ask GPT to Recommend Search Terms

```{r search-term, include=FALSE}
recommend_search_terms <- function(purpose){
  prom <- glue(
"
The purpose of the current literature review is to {purpose}. Generate search words to retrieve bibliometric data from websites such as Web of Science.

Specifications:
  1. The search words should include all resources aligned with the purpose, while effectively excluding irrelevant resources.

Provide the result in JSON format without delimiters, heading, and explanations.
"
  )

  response <- get_completion(prom)
  
  return(jsonlite::fromJSON(response))
}
```

```{r recmded-terms}
purpose <- "understand the current status of accommodations, identify gaps, and highlight effective practices and policies for the students with blindness and visual impairments"

recommend_search_terms(purpose)
```


# Import Data

- The current example data are extracted from Web of Science (WOS).

```{r data}
# import data
data <- xlsx::read.xlsx("savedrecs.xls", sheetIndex = 1)

# filter columns
data_reduced <- data %>% 
    select(Authors, Author.Full.Names, Article.Title, Source.Title, Document.Type, Conference.Title, Conference.Date, Conference.Location, Author.Keywords, Abstract, Affiliations, Publisher, Publication.Date, Publication.Year, Volume, Issue, Start.Page, End.Page)
```


# Conduct Literature Review


```{r lr-func, include=FALSE}
literature_review <- function(r_questions, bib_data, 
                              structure = "'Present Situation', 'Challenges', and 'Prospects'"){
  prom <- glue(
"
The purpose of the current literature review is to answer the 'Research Questions' below. Generate a structured summary using the 'Bibliographic Data' and by following the specifications below.

SPECIFICATION:
  1. Considering both 'Research Questions' and 'Bibliometric Data', determine the structure of summary that you think is most appropriate.
    A. However, while flexibly determining the structure of summary, make sure to exclude introduction and conclusion, and to include reference.
    B. Use {structure} as the top-level structure.
  2. Use APA style for citations (e.g., Author, Year).
  3. If there is no resource provided from 'Bibliometric Data' to be summarized under a particular heading, include the heading for the integrity of the structure and simply print the content as 'NA'.
  4. NEVER make up the content to make a pausible result. The transparency and credibility are integral parts of the literature review.
  5. If a statement needs to be double-checked by manually reading the full paper,for example due to a lack of clarity of the abstract, italicize the statement.
  6. Do not use irrelevant resource from 'Bibliometric Data'; exclude it from the Reference as well.
  7. Follow the markdown syntax in generating the final output.

Research Questions:{r_questions}
  
Bibliographic Data:
{example_data}

Provide only the summary as an output.
"
  )

  response <- get_completion(prom)
  
  return(response)
}

```

```{r lr}
# research questions
r_questions <- "
  1. What are the major accommodations currently used for students with blindness and visual impairments (BVI) in classroom settings and large-scale assessments?
    A. Levels of learning: K-12, Higher Education
    B. Type (Purposes) of assessment: Larger-scale/Classroom; Performance/Aptitude
"

# 15 example data
example_data <- data_reduced[1:10,] %>% 
  toJSON(pretty = TRUE)

# result
BVI_lr <- literature_review(
  r_questions = r_questions,
  bib_data = example_data
)
```

# Printing Out

---

```{r print, results='asis', echo=FALSE}
knitr::asis_output(BVI_lr)
```

